package com.example.rumahrahil.utils

object Constants {
    const val LOGIN = "signIn"
    const val SISWA = "user"
    const val SISWA_ID = "id_siswa_profile"
    const val SISWA_NAMA = "nama"
    const val SISWA_USERNAME = "username"
    const val SISWA_JENJANG_ID = "jenjang_id"
    const val SISWA_KELAS_ID = "kelas_id"
    const val SISWA_JURUSAN = "jurusan"
    const val SISWA_KELAS = "kelas"
    const val SISWA_ALAMAT = "alamat"
    const val SISWA_EMAIL = "email"
    const val SISWA_IMAGE = "image"
    const val TOKEN = "token"
    const val MAPEL_ID = ""
    const val BAB_ID = ""
    const val optionA = "optionA"
    const val optionB = "optionB"
    const val optionC = "optionC"
    const val optionD = "optionD"
    const val optionE = "optionE"
    const val ARRAY_BAB = ""
    const val PAKET_ID = ""
    const val PAKET_TIME = ""
    const val correctAnswer = "correctAnswer"
    const val failureAnswer = "failureAnswer"
}